// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes(in *jlexer.Lexer, out *MultiManifest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "TotalChunks":
			out.TotalChunks = int(in.Int())
		case "Digest":
			out.Digest = string(in.String())
		case "Size":
			out.Size = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes(out *jwriter.Writer, in MultiManifest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"TotalChunks\":"
		out.RawString(prefix[1:])
		out.Int(int(in.TotalChunks))
	}
	{
		const prefix string = ",\"Digest\":"
		out.RawString(prefix)
		out.String(string(in.Digest))
	}
	{
		const prefix string = ",\"Size\":"
		out.RawString(prefix)
		out.Int(int(in.Size))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MultiManifest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MultiManifest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MultiManifest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MultiManifest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes(l, v)
}
func easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes1(in *jlexer.Lexer, out *ManifestV2) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "SchemaVersion":
			out.SchemaVersion = int(in.Int())
		case "Config":
			easyjson4ef6ea8bDecode(in, &out.Config)
		case "Layers":
			if in.IsNull() {
				in.Skip()
				out.Layers = nil
			} else {
				in.Delim('[')
				if out.Layers == nil {
					if !in.IsDelim(']') {
						out.Layers = make([]struct{ Digest string }, 0, 4)
					} else {
						out.Layers = []struct{ Digest string }{}
					}
				} else {
					out.Layers = (out.Layers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 struct{ Digest string }
					easyjson4ef6ea8bDecode(in, &v1)
					out.Layers = append(out.Layers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes1(out *jwriter.Writer, in ManifestV2) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SchemaVersion\":"
		out.RawString(prefix[1:])
		out.Int(int(in.SchemaVersion))
	}
	{
		const prefix string = ",\"Config\":"
		out.RawString(prefix)
		easyjson4ef6ea8bEncode(out, in.Config)
	}
	{
		const prefix string = ",\"Layers\":"
		out.RawString(prefix)
		if in.Layers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Layers {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson4ef6ea8bEncode(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ManifestV2) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ManifestV2) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ManifestV2) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ManifestV2) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes1(l, v)
}
func easyjson4ef6ea8bDecode(in *jlexer.Lexer, out *struct{ Digest string }) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Digest":
			out.Digest = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ef6ea8bEncode(out *jwriter.Writer, in struct{ Digest string }) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Digest\":"
		out.RawString(prefix[1:])
		out.String(string(in.Digest))
	}
	out.RawByte('}')
}
func easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes2(in *jlexer.Lexer, out *ManifestV1) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "SchemaVersion":
			out.SchemaVersion = int(in.Int())
		case "FSLayers":
			if in.IsNull() {
				in.Skip()
				out.FSLayers = nil
			} else {
				in.Delim('[')
				if out.FSLayers == nil {
					if !in.IsDelim(']') {
						out.FSLayers = make([]struct{ BlobSum string }, 0, 4)
					} else {
						out.FSLayers = []struct{ BlobSum string }{}
					}
				} else {
					out.FSLayers = (out.FSLayers)[:0]
				}
				for !in.IsDelim(']') {
					var v4 struct{ BlobSum string }
					easyjson4ef6ea8bDecode1(in, &v4)
					out.FSLayers = append(out.FSLayers, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes2(out *jwriter.Writer, in ManifestV1) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SchemaVersion\":"
		out.RawString(prefix[1:])
		out.Int(int(in.SchemaVersion))
	}
	{
		const prefix string = ",\"FSLayers\":"
		out.RawString(prefix)
		if in.FSLayers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.FSLayers {
				if v5 > 0 {
					out.RawByte(',')
				}
				easyjson4ef6ea8bEncode1(out, v6)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ManifestV1) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ManifestV1) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ManifestV1) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ManifestV1) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes2(l, v)
}
func easyjson4ef6ea8bDecode1(in *jlexer.Lexer, out *struct{ BlobSum string }) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "BlobSum":
			out.BlobSum = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ef6ea8bEncode1(out *jwriter.Writer, in struct{ BlobSum string }) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"BlobSum\":"
		out.RawString(prefix[1:])
		out.String(string(in.BlobSum))
	}
	out.RawByte('}')
}
func easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes3(in *jlexer.Lexer, out *Manifest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ContentType":
			out.ContentType = string(in.String())
		case "Data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				out.Data = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes3(out *jwriter.Writer, in Manifest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ContentType\":"
		out.RawString(prefix[1:])
		out.String(string(in.ContentType))
	}
	{
		const prefix string = ",\"Data\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Data)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Manifest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Manifest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ef6ea8bEncodeGithubComElasticIoHavenInternalTypes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Manifest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Manifest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ef6ea8bDecodeGithubComElasticIoHavenInternalTypes3(l, v)
}
